import { withPageAuthRequired } from "@auth0/nextjs-auth0"
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default withPageAuthRequired(
  async function AuthRequired({
    children,
  }: Readonly<{
    children: React.ReactNode
  }>) {
  return (
    <body className={`bg-stone-200 h-screen w-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}>
      {children}
    </body>
  )
  }
)